image: repo.tok.ipp.cas.cz:5050/tomography/core/tomotok-sphinx:latest

stages:
  - test
  - deploy

test_code:
  stage: test
  script:
  - python3 -m unittest discover -s tomotok -p "test_*.py"

test_pages:
  stage: test
  script:
  - sphinx-build -b html docs/source public
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - sphinx-build -b html docs/source public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
